### PR TITLE
Inventory Manipulation and User Experience/Friendliness

### PR DESCRIPTION
**Pull request by ThommyDude**
Things this update does:

- Adds a "Current Level" behind the "Current XP" input that updates as the xp changes. Making it clearer as to what level the Bro will be after the editing.
- Allows editing of specific items counts instead of just maxing everything out.
- Not giving the ability to give the player the '??????' Pants or '??????' Badge through new specific inventory manipulation nor through the max everything button as these gear items are bugged and _CAN_, although unlikely, corrupt save files.
- Removes all the '_' from the different input titles, making them look less like variable names and more like descriptions.

Tested it a handful of times myself haven't had any errors or unexpected thing happen in-game after editing my save with this updated version. So to my knowledge I haven't broken anything with this update.
The only thing that might need further changes is in the styling, but I'm a backend coder, I don't make thing pretty, I make things work 😅

### CODE REVIEW

**Comment by ThommyDude** [comment]
In case you don't want these changes or anything, I would like to ask for permission to host my changed/updated version on my own githubpages page so it's still available online somewhere for whoever else is playing MLSS3DS in 2020 😂

**Comment by ThommyDude** [comment]
Suddenly, everything broke. Levels aren't making sense and Luigi's Stash bonus keeps getting overwritten... I'll create a new PR when I've figured this out.

**Comment by cefoFintecimal** [comment]
Hi there, nice to meet you.

I started this project to practice JS at the time and I admit that it has bad practices, mostly my goal was only to get items and beans once I finish the game

the item ??? leave it as a curiosity, it does not affect you in anything if you equip it or not and you can sell it

I have another project in fact in react in case you are looking for more structured but the offsets are for the dream team game

Regards! :)

**Comment by Cefo14** [comment]
Hi there, nice to meet you.

I started this project to practice JS at the time and I admit that it has bad practices, mostly my goal was only to get items and beans once I finish the game

the item ??? leave it as a curiosity, it does not affect you in anything if you equip it or not and you can sell it

I have another project in fact in react in case you are looking for more structured but the offsets are for the dream team game

Regards! :)

**Comment by ThommyDude** [comment]
Cool, I figured out what went wrong btw, so I might create a new PR tomorrow for it. Check it out [here](https://github.com/ThommyDude/MLSS_SE).

Bad practices are what the good ones are build on, so don't worry. Also, a little janky code never hurt anyone ;P

> the item ??? leave it as a curiosity, it does not affect you in anything if you equip it or not and you can sell it

Oh? I might add them back in then. I remember reading something about these items a long time ago saying they could mess up your save, but I might be remembering it wrong then 🤷🏻‍♂️

I have next to zero experience in React, but I might take a peek anyway!

-Thommy

**Pull request closed without merging**
