### PR TITLE
MLSS_SE Update

### PR DESCRIPTION
**Pull request by ThommyDude**
Alright, take 2!

Change list:
- README.md
   - Small spelling fix because it bothered me 🤷🏻‍♂️
- app.css
   - Add a bunch of new classes for new elements.
   - Add styling for the new options menu sliding all the content to the side.
- index.html
   - Add elements for the new options menu
   - Add wrapper element
   - Add script-tags to include the two extra lists
- ItemList.js
   - **New file**
   - A list of all the items in the game and their respective id.
      - I manually edited the code to give every item an incremental amount so I could figure out which ID was which ITEM... This took WAY longer than I'm willing to admit!
- Levels.js
   - **New file**
   - A list of the amount of EXP needed to reach a certain level for each Bro.
      - Found out that this data is based off the GBA game, so it's SLIGHTLY off compared to the new one for some reason. This is why I've added an option in the new options menu to turn off showing the approximate lvl. (Or you can just ignore it)
- Offsets.js
   - Changes "Items" to "Consumables" due to EVERY item being an item, yet these items are the only consumables, made more sense to me while working.
   - Changed "Badjes" to "Badges". Just a spelling mistake fix.
- app.js
   - Added code for the new Inventory Editor.
   - Added code for the new Options Menu.
      - Added code for the new Options IN the Options Menu.
   - Made all `if`/`else` statements use curly brackets (`{}`) for consistency as well as fixing a slight bug caused by a change I made.
   - Changed `addPJ` to `addBro` because I didn't understand what PJ stood for in this context and it kept confusing me 😅🤷🏻‍♂️

I think that's about all the changes I made.
Everything seems to work without any problems **_for real this time_** so this should be ready to merge!

Let me know if you want me to change anything before the merge.

PS. The options get reset every time you leave/reload the page simply because I didn't want to make a session/cookie for it because then you'd need to add all the new GDPR friendly cookie warnings and texts. This way it gets reset which might get a little annoying, but it skips a LOT of the leg work.

### CODE REVIEW

**Review by Cefo14 — APPROVED** [review]
Hey, what's up, Tommy? Sorry I'm late. I've been doing some work D:

Thank you for taking the time to make those corrections and improvements, the pr has been approved :)

PD: about the values reset when restarting the page I think it's ok, normally I estimate that the flow is edit -> download -> be happy xD

although we could still put it in a localstorage if persistence of the data was required, the files are less than >5MB

Regards!  have a good start to the week :D

**Comment by ThommyDude** [comment]
Hey Cefo!

> Sorry I'm late. I've been doing some work D:

No worries!
In the current state of the world, I'm just happy for you to HAVE work.

> Thank you for taking the time to make those corrections and improvements, the pr has been approved :)

Awesome, I can't actually merge it because I don't have that right in your repo, so if you want to merge it just go right ahead!

> PD: about the values reset when restarting the page I think it's ok, normally I estimate that the flow is edit -> download -> be happy xD
> 
> although we could still put it in a localstorage if persistence of the data was required, the files are less than >5MB

Yeah, that's kinda my assumption too, which is why I didn't really feel like messing with it at this point 😂

Thanks! Have a good one yourself!

**Comment by Cefo14** [comment]
Hi ThommyDude, good morning,  sorry for my absence D:

I add you as a contributor and I appreciate that you took the time to make those arrangements. <3

I hope you have a good week
Regards! :D

**Comment by ThommyDude** [comment]
Cool, thanks!
And don't worry about the absence, the world is crazy right now so these things happen.

Have a good one, Cefo!

**Pull request merged**
